# Generated by Django 5.0 on 2026-04-09 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_result', models.TextField()),
                ('status', models.CharField(choices=[('не начат', 'не начат'), ('в процессе', 'в процессе'), ('завершен', 'завершен')], db_index=True, max_length=50)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('specialist', 'specialist'), ('project_manager', 'project_manager'), ('customer', 'customer')], db_index=True, max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('qa', 'qa')], db_index=True, max_length=50)),
                ('required_level', models.CharField(choices=[('junior', 'junior'), ('middle', 'middle'), ('senior', 'senior')], db_index=True, max_length=50)),
                ('desired_level', models.CharField(blank=True, choices=[('junior', 'junior'), ('middle', 'middle'), ('senior', 'senior')], db_index=True, max_length=50, null=True)),
                ('specialists_count', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='db.project')),
            ],
            options={
                'db_table': 'project_requirements',
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirementDesiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Docker', 'Docker'), ('C++', 'C++')], db_index=True, max_length=100)),
                ('project_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_skills', to='db.projectrequirement')),
            ],
            options={
                'db_table': 'project_requirement_desired_skills',
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirementRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Docker', 'Docker'), ('C++', 'C++')], db_index=True, max_length=100)),
                ('project_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='db.projectrequirement')),
            ],
            options={
                'db_table': 'project_requirement_required_skills',
            },
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'specialist'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='specialist_profile', serialize=False, to='db.user')),
                ('experience_years', models.PositiveIntegerField()),
                ('profession', models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('qa', 'qa')], db_index=True, max_length=50)),
                ('level', models.CharField(choices=[('junior', 'junior'), ('middle', 'middle'), ('senior', 'senior')], db_index=True, max_length=50)),
                ('is_busy', models.BooleanField(default=False)),
                ('busy_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specialist_profile',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.PositiveIntegerField()),
                ('quality', models.CharField(choices=[('ужасно', 'ужасно'), ('плохо', 'плохо'), ('нормально', 'нормально'), ('хорошо', 'хорошо'), ('отлично', 'отлично')], db_index=True, max_length=50)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='db.project')),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.RESTRICT, related_name='reports_created', to='db.user')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('specialist', 'specialist'), ('project_manager', 'project_manager'), ('customer', 'customer')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('рекомендован', 'рекомендован'), ('предложен', 'предложен'), ('согласился', 'согласился'), ('работает', 'работает'), ('завершил', 'завершил')], db_index=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('skill_match_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='db.project')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_assignments', to='db.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='db.user')),
            ],
            options={
                'db_table': 'project_assignments',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'project_manager'}, on_delete=django.db.models.deletion.RESTRICT, related_name='managed_projects', to='db.user'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'admin'), ('specialist', 'specialist'), ('project_manager', 'project_manager'), ('customer', 'customer')], db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='db.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='db.user')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Docker', 'Docker'), ('C++', 'C++')], db_index=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='db.user')),
            ],
            options={
                'db_table': 'user_skills',
            },
        ),
        migrations.AddConstraint(
            model_name='projectrequirement',
            constraint=models.CheckConstraint(check=models.Q(('specialists_count__gt', 0)), name='chk_project_requirements_specialists_count'),
        ),
        migrations.AddConstraint(
            model_name='projectrequirementdesiredskill',
            constraint=models.UniqueConstraint(fields=('project_requirement', 'skill'), name='uq_req_desired_skills'),
        ),
        migrations.AddConstraint(
            model_name='projectrequirementrequiredskill',
            constraint=models.UniqueConstraint(fields=('project_requirement', 'skill'), name='uq_req_required_skills'),
        ),
        migrations.AddConstraint(
            model_name='specialistprofile',
            constraint=models.CheckConstraint(check=models.Q(('experience_years__gte', 0)), name='chk_specialist_profile_experience_years'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(('total_hours__gte', 0)), name='chk_reports_total_hours'),
        ),
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='chk_project_assignments_dates'),
        ),
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.CheckConstraint(check=models.Q(('skill_match_percent__isnull', True), models.Q(('skill_match_percent__gte', 0), ('skill_match_percent__lte', 100)), _connector='OR'), name='chk_project_assignments_skill_match_percent'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('budget__gte', 0)), name='chk_projects_budget'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='chk_projects_dates'),
        ),
        migrations.AddConstraint(
            model_name='userskill',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='uq_user_skills_user_skill'),
        ),
    ]
