# Generated by Django 5.0 on 2026-04-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequirement',
            name='profession',
            field=models.CharField(choices=[('product_manager', 'Product Manager'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('fullstack_developer', 'Full-stack Developer'), ('mobile_developer', 'Mobile Developer'), ('crm_erp_developer', 'CRM / ERP Developer'), ('qa_engineer', 'QA Engineer'), ('test_automation_engineer', 'Test Automation Engineer'), ('devops_engineer', 'DevOps Engineer'), ('ai_engineer', 'AI Engineer'), ('data_analyst', 'Data Analyst'), ('bi_developer', 'BI Developer'), ('data_engineer', 'Data Engineer'), ('data_scientist', 'Data Scientist'), ('security_engineer', 'Security Engineer'), ('cloud_engineer', 'Cloud Engineer'), ('release_manager', 'Release Manager')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectrequirementdesiredskill',
            name='skill',
            field=models.CharField(choices=[('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('python', 'Python'), ('sql', 'SQL'), ('go', 'Go'), ('java', 'Java'), ('csharp', 'C#'), ('rust', 'Rust'), ('bash_shell', 'Bash / Shell'), ('html_css', 'HTML / CSS'), ('php', 'PHP'), ('kotlin', 'Kotlin'), ('swift', 'Swift'), ('cpp', 'C++'), ('node_js', 'Node.js'), ('react', 'React'), ('vue_js', 'Vue.js'), ('vite', 'Vite'), ('flutter', 'Flutter'), ('grpc', 'gRPC'), ('sqlalchemy', 'SQLAlchemy'), ('mongodb', 'MongoDB'), ('clickhouse', 'ClickHouse'), ('kafka', 'Kafka'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('docker', 'Docker')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectrequirementrequiredskill',
            name='skill',
            field=models.CharField(choices=[('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('python', 'Python'), ('sql', 'SQL'), ('go', 'Go'), ('java', 'Java'), ('csharp', 'C#'), ('rust', 'Rust'), ('bash_shell', 'Bash / Shell'), ('html_css', 'HTML / CSS'), ('php', 'PHP'), ('kotlin', 'Kotlin'), ('swift', 'Swift'), ('cpp', 'C++'), ('node_js', 'Node.js'), ('react', 'React'), ('vue_js', 'Vue.js'), ('vite', 'Vite'), ('flutter', 'Flutter'), ('grpc', 'gRPC'), ('sqlalchemy', 'SQLAlchemy'), ('mongodb', 'MongoDB'), ('clickhouse', 'ClickHouse'), ('kafka', 'Kafka'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('docker', 'Docker')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='profession',
            field=models.CharField(choices=[('product_manager', 'Product Manager'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('fullstack_developer', 'Full-stack Developer'), ('mobile_developer', 'Mobile Developer'), ('crm_erp_developer', 'CRM / ERP Developer'), ('qa_engineer', 'QA Engineer'), ('test_automation_engineer', 'Test Automation Engineer'), ('devops_engineer', 'DevOps Engineer'), ('ai_engineer', 'AI Engineer'), ('data_analyst', 'Data Analyst'), ('bi_developer', 'BI Developer'), ('data_engineer', 'Data Engineer'), ('data_scientist', 'Data Scientist'), ('security_engineer', 'Security Engineer'), ('cloud_engineer', 'Cloud Engineer'), ('release_manager', 'Release Manager')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.CharField(choices=[('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('python', 'Python'), ('sql', 'SQL'), ('go', 'Go'), ('java', 'Java'), ('csharp', 'C#'), ('rust', 'Rust'), ('bash_shell', 'Bash / Shell'), ('html_css', 'HTML / CSS'), ('php', 'PHP'), ('kotlin', 'Kotlin'), ('swift', 'Swift'), ('cpp', 'C++'), ('node_js', 'Node.js'), ('react', 'React'), ('vue_js', 'Vue.js'), ('vite', 'Vite'), ('flutter', 'Flutter'), ('grpc', 'gRPC'), ('sqlalchemy', 'SQLAlchemy'), ('mongodb', 'MongoDB'), ('clickhouse', 'ClickHouse'), ('kafka', 'Kafka'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('docker', 'Docker')], db_index=True, max_length=100),
        ),
    ]
