# Generated by Django 5.0 on 2026-04-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_projectrequirement_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequirement',
            name='profession',
            field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('qa', 'qa')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectrequirementdesiredskill',
            name='skill',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Docker', 'Docker'), ('C++', 'C++')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectrequirementrequiredskill',
            name='skill',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Docker', 'Docker'), ('C++', 'C++')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='profession',
            field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('qa', 'qa')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Docker', 'Docker'), ('C++', 'C++')], db_index=True, max_length=100),
        ),
    ]
